version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: local-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpassword
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: local-adminer
    restart: unless-stopped
    ports:
      - '8080:8080'

volumes:
  mysql_data:
